backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
publish_mode: editorial_workflow
# This line should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "careers" # Used in routes, e.g., /admin/collections/blog
    label: "Careers" # Used in the UI
    folder: "models/careers" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: false,
        }
      - {
          label: "Responsibilites",
          name: "responsibilities",
          widget: "list",
          required: false,
          field:
            {
              label: "Responsibility",
              name: "responsibility",
              widget: "string",
          required: false,

            },
        }
      - {
          label: "Requirements",
          name: "requirements",
          widget: "list",
          required: false,
          field:
            { label: "Requirement", name: "requirement", widget: "string", required: false,},
        }
      - {
          label: "Positions",
          name: "positions",
          widget: "list",
          required: false,
          field: { label: "Position", name: "position", widget: "string", required: false, },
        }
      - { label: "Note", name: "note", widget: "text", required: false }

  - name: "work" # Used in routes, e.g., /admin/collections/blog
    label: "Work" # Used in the UI
    folder: "models/work" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Project Title", name: "title", widget: "string" }
      - {
          label: "Project Category",
          name: "category",
          widget: "select",
          multiple: true,
          options:
            [
              "Social",
              "Ecommerce",
              "Design",
              "Development",
              "Creative",
              "Consultancy",
            ],
        }
      - {
          label: "Thumbnail Image",
          name: "thumbnail",
          widget: "image",
          default: "/images/uploads/placeholder.jpg",
        }
      - { label: "Client", name: "client", widget: "string" }
      - { label: "Client Description", name: "description", widget: "text" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Work", name: "work", widget: "string" }
      - { label: "Team", name: "team", widget: "string" }
      - {
          label: "Project Link",
          name: "link",
          widget: "string",
          required: false,
        }
      - { label: "The Challenge", name: "challenge", widget: "text" }
      - { label: "The Solution", name: "solution", widget: "text" }
      - {
          label: "Video Link",
          name: "video",
          widget: "string",
          required: false,
        }
      - {
          label: "Main Image Gallery",
          name: "mainImages",
          widget: "list",
          field:
            {
              label: "Image",
              name: "image",
              widget: "image",
              default: "/images/uploads/cover-placeholder.png",
            },
          required: false,
        }
      - {
          label: "Square Image Gallery",
          name: "galleryImages",
          widget: "list",
          field:
            {
              label: "Image",
              name: "image",
              widget: "image",
              default: "/images/uploads/placeholder.jpg",
            },
          required: false,
          hint: "Aspect Ratio: 1:1",
        }
      - {
          label: "Vertical Video Gallery",
          name: "galleryVideos",
          widget: "list",
          field: { label: "Video", name: "video", widget: "string" },
          required: false,
          hint: "Aspect Ratio: 9:19.5",
        }
