backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
publish_mode: editorial_workflow
# This line should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "jobs" # Used in routes, e.g., /admin/collections/blog
    label: "Job" # Used in the UI
    folder: "models/jobs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "json"
    format: "json"
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "job" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: false,
        }
      - {
          label: "Responsibilites",
          name: "responsibilities",
          widget: "list",
          field: {label: Responsibility, name: responsibility, widget: "string"}
          required: false,
        }
      - {
          label: "Requirements",
          name: "requirements",
          widget: "list",
          field: {label: Requirement, name: requirement, widget: "string"}
          required: false,
        }
      - {
          label: "Positions",
          name: "positions",
          widget: "list",
          field: {label: Position, name: position, widget: "string"}
          required: false,
        }
      - { label: "Note", name: "note", widget: "text", required: false }
