backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
publish_mode: editorial_workflow
# This line should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "careers" # Used in routes, e.g., /admin/collections/blog
    label: "Careers" # Used in the UI
    folder: "models/careers" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: false,
        }
      - {
          label: "Responsibilites",
          name: "responsibilities",
          widget: "list",
          required: false,
          hint: "Enter comma separated values",
        }
      - {
          label: "Requirements",
          name: "requirements",
          widget: "list",
          required: false,
          hint: "Enter comma separated values",
        }
      - {
          label: "Positions",
          name: "positions",
          widget: "list",
          required: false,
          hint: "Enter comma separated values",
        }
      - { label: "Note", name: "note", widget: "text", required: false }

  - name: "work" # Used in routes, e.g., /admin/collections/blog
    label: "Work" # Used in the UI
    folder: "models/work" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Project Title", name: "title", widget: "string" }
      - {
          label: "Thumbnail Image",
          name: "thumbnail",
          widget: "image",
          default: "/images/uploads/placeholder.svg",
        }
      - { label: "Client", name: "client", widget: "string" }
      - { label: "Client Description", name: "description", widget: "text" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Work", name: "work", widget: "string" }
      - { label: "Team", name: "team", widget: "string" }
      - { label: "Project Link", name: "link", widget: "string" }
      - { label: "The Challenge", name: "challenge", widget: "text" }
      - { label: "The Solution", name: "solution", widget: "text" }
